-- INSERT INTO PRODUCT(CODE) VALUES ('hdgta67g2ebadsb');
-- INSERT INTO PRODUCT(CODE) VALUES ('asdasdwer23rfds');
-- INSERT INTO PRODUCT(CODE) VALUES ('gjkjtyurthff333');
-- INSERT INTO PRODUCT(CODE) VALUES ('dsfdsfewrtwrter');
-- INSERT INTO PRODUCT(CODE) VALUES ('43t5grtgs443fff');

--
-- INSERT INTO ORDER(CODE) VALUES ('hdgta67g2ebadsb');
-- INSERT INTO PRODUCT(CODE) VALUES ('asdasdwer23rfds');
-- INSERT INTO PRODUCT(CODE) VALUES ('gjkjtyurthff333');
-- INSERT INTO PRODUCT(CODE) VALUES ('dsfdsfewrtwrter');
-- INSERT INTO PRODUCT(CODE) VALUES ('43t5grtgs443fff');

-- INSERT INTO CUSTOMER(E_MAIL, EDUCATION, GENDER, POST_CODE) VALUES ('email1@gmail.com', 'Higher', 'Male', '31-350');
-- INSERT INTO CUSTOMER(E_MAIL, EDUCATION, GENDER, POST_CODE) VALUES ('email5@default.com', 'General', 'Female', '22-222');
-- INSERT INTO CUSTOMER(E_MAIL, EDUCATION, GENDER, POST_CODE) VALUES ('email3@gmail.com', 'Secondary', 'Male', '33-222');
-- INSERT INTO CUSTOMER(E_MAIL, EDUCATION, GENDER, POST_CODE) VALUES ('email4@default.com', 'Secondary', 'Female', '31-356');
-- INSERT INTO CUSTOMER(E_MAIL, EDUCATION, GENDER, POST_CODE) VALUES ('winio94@gmail.com', 'General', 'Male', '31-312');