INSERT INTO STUDENT(FIRSTNAME, SECONDNAME) VALUES('Mateusz', 'B');

INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (true, 100);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (true, 400);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (false, 2);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (false, 5);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (true, 5);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (true, 200);
INSERT INTO SITE_ENTRY(IS_DIRECT_ENTRY,VISIT_TIME) VALUES (true, 900);